# Разработка модели машинного обучения

## Импортирование библиотек

In [1]:
# для работы с датафреймами
import pandas as pd

# для работы с массивами
import numpy as np

# для преобразования текста
from nltk.tokenize import sent_tokenize

# вспомогательные функции
from function import *

# для работы с датасетами
from datasets import Dataset, DatasetDict

# токенизатор и модель
from transformers import T5Tokenizer, T5ForConditionalGeneration
# аргументы для обучения, и трейнер
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments
# коллатор
from transformers import DataCollatorForSeq2Seq

# основной модуль для нейронных сетей
import torch

# модуль с метрикой оценивания
import evaluate
# модуль для модели сравнения
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
# модуль для разбиения предложений на слвоа
from nltk.tokenize import word_tokenize
# косинусное сходство
from sklearn.metrics.pairwise import cosine_similarity
# для работы с векторами
import numpy as np

c:\Users\Илья\Desktop\nlp\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

WARNING:tensorflow:From c:\Users\Илья\Desktop\nlp\.venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Илья\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Илья\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Определяю устройство, на котором будут производиться вычисления:

In [2]:
torch.cuda.is_available()

True

In [3]:
# получаю девайс
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# вывожу девайс
print(device)

cuda

Описание вспомогательных функций *(реализованных в файле `function.py`)*

```py
# функция для сравнения двух текстов
def get_similarity(text1: str, 
                   text2: str, 
                   model: str | Doc2Vec, 
                   prep_flag: bool = True, 
                   preprocess: Callable[[str], str] = get_input):
    '''
    Функция для получения схожести двух текстов
    ===
        Args:
            - text1 (str): первый текст в строковом формате
            - text2 (str): второй текст в строковом формате
            - model (str|Doc2Vec): модель в формате doc2vec объекта 
                                  либо путь к ней в строковом формате

        Returns:
            - float: сходство между текстами (от 1 до -1)
    '''
    # проверка формата текста 1
    if not isinstance(text1, str):
        raise TypeError(f'text1 должен быть в строковом формате, а не {type(text1)}')
    # проверка формата текста 2
    if not isinstance(text1, str):
        raise TypeError(f'text1 должен быть в строковом формате, а не {type(text1)}')
    # проверка формата модели
    if not isinstance(model, (str, Doc2Vec)):
        raise TypeError(f'model должна быть в формате Doc2Vec, либо в виде строкового путя, а не {type(model)}')
    # если модель в виде путя
    if type(model) == str:
        # проверяем, что файл существует
        if os.path.exists(model):
            # пробуем загрузить модель через try: except
            try:
                # загружаем модель из файла
                model = Doc2Vec.load(model)
            # если не получилось загрузить, выводим ошибку
            except Exception as e:
                raise ValueError(f'Ошибка! не удалось загрузить модель, проверьте ваш файл!\n{e}')
        # если путь не существует:
        else:
            # выводим ошибку
            raise ValueError('Ошибка! Файла с моделью не существует, проверьте правильность написания!')
    # если стоит метка о обработке данных
    if prep_flag:
        text1 = preprocess(text1)
        text2 = preprocess(text2)
    # вычисляем эмбеддинг
    inferred_vector1 = model.infer_vector(word_tokenize(text1.lower())).reshape(1,-1)
    inferred_vector2 = model.infer_vector(word_tokenize(text2.lower())).reshape(1,-1)
    # # получаем сходство
    return cosine_similarity(inferred_vector1, inferred_vector2).item()
```

```py
# функция для поиска топ 3 схожих статей
def find_top_similar(df: pd.DataFrame, text: str, model: Doc2Vec, top_n: int = 3) -> pd.DataFrame:
    '''
    Находит топ-N наиболее схожих эмбеддингов и их summary.

    Параметры:
        df (pd.DataFrame): Датафрейм с колонками 'summary' и 'embedding'.
        input_embedding (np.ndarray): Входной эмбеддинг для сравнения.
        top_n (int): Количество наиболее схожих результатов (по умолчанию 3).

    Возвращает:
        tuple
    '''
    # получаем эмбеддинг
    input_embedding = model.infer_vector(word_tokenize(get_input(text))).reshape(1,-1)
    # список всех схожестей
    similarities = []
    # проходимся по всему датафрейму
    for i in range(df.shape[0]):
        similarities.append(cosine_similarity(input_embedding, df['embedding'].loc[i]).item()*100)
    # Добавляем столбец с косинусной схожестью в датафрейм
    df['similarity'] = similarities
    
    # Сортируем датафрейм по убыванию схожести и выбираем топ-N
    top_similar = df.sort_values(by='similarity', ascending=False).head(3)
    summaries = top_similar['summary'].tolist()
    top_similarities = [round(sim, 2) for sim in top_similar['similarity'].tolist()]
    headers = [' '.join(word_tokenize(summary)) for summary in summaries]

    # Возвращаем только нужные колонки
    return top_similarities, headers
```

## Загрузка данных

In [4]:
# загружаю тренировочную выборку
train_dataset = Dataset.from_parquet("Dataset/train.parquet")
# валидационную выборку
validation_dataset = Dataset.from_parquet("Dataset/validation.parquet")
# тестовую выборку
test_dataset = Dataset.from_parquet("Dataset/test.parquet")
# загружаю тренировочную выборку
train_dataset = Dataset.from_parquet("Dataset/train.parquet")
# валидационную выборку
validation_dataset = Dataset.from_parquet("Dataset/validation.parquet")
# тестовую выборку
test_dataset = Dataset.from_parquet("Dataset/test.parquet")

# объединяю все выборки в объект Dataset
dataset = DatasetDict({
    "train": train_dataset,
    "validation": validation_dataset,
    "test": test_dataset
})
# вывожу структуру получившегося набора данных
dataset

DatasetDict({
    train: Dataset({
        features: ['text_path', 'annotation_path', 'tags_path', 'text', 'summary', 'tag', 'text_all_symb', 'summary_all_symb', 'tag_all_symb', 'text_clean', 'summary_clean', 'tag_clean', 'text_words', 'summary_words', 'tag_words', 'id', 'processed_text', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 329
    })
    validation: Dataset({
        features: ['text_path', 'annotation_path', 'tags_path', 'text', 'summary', 'tag', 'text_all_symb', 'summary_all_symb', 'tag_all_symb', 'text_clean', 'summary_clean', 'tag_clean', 'text_words', 'summary_words', 'tag_words', 'id', 'processed_text', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 41
    })
    test: Dataset({
        features: ['text_path', 'annotation_path', 'tags_path', 'text', 'summary', 'tag', 'text_all_symb', 'summary_all_symb', 'tag_all_symb', 'text_clean', 'summary_clean', 'tag_clean', 'text_words', 'summary_words', 'tag_words', 'id', 'processed_text', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 42
    })
})

## Подбор алгоритма обучения

### Модель суммаризации

Передо мной стоит задача `суммаризации` текста. Это значит, что надо реализовать нейронную сеть, которая будет находить и выписывать краткое содержание текста. Для этого я буду использовать предобученную модель `"sarahai/ruT5-base-summarizer"`, которую настрою работать на своих данных

Модель `RuT5` адаптирована для работы с русским языком, что важно для корректной обработки и генерации текста на русском

Архитектура `T5` (`Text-To-Text Transfer Transformer`) - это архитектура которая хорошо справляется с задачами преобразования текста, включая суммаризацию

Использование предобученной модели позволяет сэкономить время и ресурсы, так как модель уже обучена на большом объеме данных, и может быть дообучена (`fine-tunned`) на собственном наборе данных для решения более конкретной задачи

### Модель сравнения

Для `сравнения` текстов, я буду использовать `эмбеддинги` текста - векторные представления, а для извлечения `эмбеддингов` я буду использовать модель `Doc2Vec`

`Doc2Vec` преобразует тексты в `вектора`, что позволяет сравнивать их между собой (в моем случае я буду использовать метрику `косинусного сходства`)

В отличие от других, более простых методов, `Doc2Vec` учитывает `семантику` и `контекст` слов, что делает сравнение более точным

Благодаря тому, что я буду обучать модель на своем `корпусе данных`, модель сможет более точно сравнивать именно тексты заданного формата (`статьи`)

### Метрики для суммаризации текста

Для суммаризации одной из наиболее часто используемых метрик является оценка `ROUGE` (сокращение от `Recall-Oriented Understudy for Gisting Evaluation`). Основная идея этой метрики заключается в сравнении сгенерированного текста с набором эталонных текстов, которые обычно создаются людьми. Чтобы сделать ее более точной, предположим, что мы хотим сравнить следующие две строчки:

In [5]:
generated_summary = "I absolutely loved reading the Hunger Games"
reference_summary = "I loved reading the Hunger Games"

Одним из способов их сравнения может быть подсчет `количества перекрывающихся слов`, которых в данном случае будет 6. Однако это несколько грубовато, поэтому вместо этого `ROUGE` основывается на вычислении оценок `precision` и `recall` для перекрытия

Для `ROUGE` `recall` измеряет, насколько эталонное резюме соответствует `сгенерированному`. Если мы просто сравниваем слова, `recall` можно рассчитать по следующей формуле:

$$\text{Recall} = \frac{\text{Number of overlapping words}}{\text{Total number of words in reference summary}}$$

Для нашего простого примера выше эта формула дает идеальный `recall` 6/6 = `1`; то есть все слова в эталонном тексте были получены моделью. Это может показаться замечательным, но представьте, если бы сгенерированный нами текст был “I really really loved reading the Hunger Games all night”. Это тоже дало бы идеальный `recall`, но, возможно, было бы хуже, поскольку было бы многословным. Чтобы справиться с этими сценариями, мы также вычисляем `precision`, которая в контексте `ROUGE` измеряет, насколько `сгенерированное` резюме было `релевантным`:

$$\text{Precision} = \frac{\text{Number of overlapping words}}{\text{Total number of words in generated summary}}$$

Если применить это к нашему подробному тексту, то `precision` составит 6/10 = 0,6, что значительно хуже, чем `precision` 6/7 = 0,86, полученная при использовании более короткого текста. На практике обычно вычисляют и `precision`, и `recall`, а затем `F1-score` (среднее гармоническое из `precision` и `recall`)

Загружаю метрику `ROUGE`:

In [6]:
# загружаю используемую метрику
rouge_score = evaluate.load('rouge')

Затем мы можем использовать функцию `rouge_score.compute()`, чтобы рассчитать все метрики сразу:

In [9]:
# считаем метрики примеров
scores = rouge_score.compute(
    predictions=[generated_summary],
    references=[reference_summary]
)
# вывожу получившиеся метрики
scores

{'rouge1': 0.923076923076923,
 'rouge2': 0.7272727272727272,
 'rougeL': 0.923076923076923,
 'rougeLsum': 0.923076923076923}

## Работа с нейронной сетью

#### Модель суммаризации

Для начала, надо инициализировать саму `модель` и ее `токенизатор`:

In [7]:
# имя модели
model_name = "sarahai/ruT5-base-summarizer"
# инициализируем модель
model = T5ForConditionalGeneration.from_pretrained(model_name)
# инициализирую токенизатор
tokenizer = T5Tokenizer.from_pretrained(model_name)

Теперь, надо назначить вычислительное устройство для модели (его я определил выше):

In [8]:
# назначаю устройство и вывожу архитектуру модели
model.to(device)

T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32128, bias=False)
)

Дообучение `ruT5` с `API` `Trainer`

In [9]:
# назначаю кол-во батчей
batch_size = 8
# кол-во эпох
epochs = 30
# функция потерь
logging_steps = len(dataset['train']) // batch_size
name = model_name.split('/')[-1]
print(name)

ruT5-base-summarizer

Теперь, нужно создать объект `Seq2SeqTrainingArguments`, чтобы заполнить гиперпараметры модели:

In [ ]:
# объект с гиперпараметрами
args = Seq2SeqTrainingArguments(
    output_dir='model-4-summary',
    overwrite_output_dir=True,
    eval_strategy='epoch',                     # оценка после каждой эпохи
    per_device_train_batch_size=batch_size,     # кол-во тренировочных батчей
    per_device_eval_batch_size=batch_size,      # кол-во батчей для оценки
    gradient_accumulation_steps=2,              # кол-во шагов накопления градиента до обновления
    torch_empty_cache_steps=4,                  # oчистка кэша GPU через каждые 4 шага
    learning_rate=1e-4,                         # скорость обучения
    num_train_epochs=epochs,                    # кол-во эпох
    logging_steps=logging_steps,                # частота логов
    seed=42,                                    # сид для воспроизводимости результатов
    fp16=True,       # TODO тест fp4-fp8        # использование mixed precision для ускорения обучения
    weight_decay=0.01,                          # отложенные весаL2-регуляризация для предотвращения переобучения
    optim='adamw_torch',                        # оптимизатор
)

Следующее, что нужно сделать, это предоставить тренеру функцию `compute_metrics()`, чтобы оценить нашу модель во время обучения. Для суммаризации это немного сложнее, чем просто вызвать `rouge_score.compute()` для прогнозов модели, поскольку нужно декодировать выводы и метки в текст, прежде чем вычислить оценку `ROUGE`. Следующая функция делает именно это, а также использует функцию `sent_tokenize()` из `nltk` для разделения предложений резюме символом новой строки

In [ ]:
# функция для вычисления метрик
def compute_metrics(eval_pred):
    # получаем предсказания и их метки
    predictions, labels = eval_pred
    # Если predictions — это кортеж, берем первый элемент (логи)
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Преобразуем логи в индексы токенов с помощью argmax
    predicted_token_ids = np.argmax(predictions, axis=-1)
    # декодируем сгенерированные суммаризации в текст
    decoded_preds = tokenizer.batch_decode(predicted_token_ids, skip_special_tokens=True)
    # заменяем -100 в метках, тк декодировать их нельзя
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    # декодируем эталонные изложения 
    decoded_summary = tokenizer.batch_decode(labels, skip_special_tokens=True)
    # ROUGE ожидает символ новой строки после каждого предложения
    decoded_preds = ['\n'.join(sent_tokenize(pred.strip())) for pred in decoded_preds]
    decoded_summary = ['\n'.join(sent_tokenize(label.strip())) for label in decoded_summary]
    
    # вычисляем метрики ROUGE
    result = rouge_score.compute(
        predictions=decoded_preds,
        references=decoded_summary,
        use_stemmer=True            # проверить и с ним, и без него
    )

    # получаем оценки
    result = {k: v*100 for k, v in result.items()}
    return {k: round(v,4) for k,v in result.items()}

Также, для обучения модели необходим `коллатор`, который будет сдвигать метки на 1 каждый шаг

In [12]:
# инициализируем коллатор
collator = DataCollatorForSeq2Seq(tokenizer, model)

Получаем датасет для обучения модели

In [13]:
# убираем лишние колонки
train_data = dataset.select_columns(['input_ids', 'attention_mask', 'labels'])
# выводим датасет
train_data

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 329
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 41
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 42
    })
})

Теперь, надо создать объект `Trainer` для запуска обучения модели

In [15]:
# объект trainer 
trainer = Seq2SeqTrainer(
    model,                                  # модель
    args,                                   # тренировочные аргументы
    train_dataset=train_data['train'],      # датасет для обучения модели
    eval_dataset=train_data['validation'],  # датасет для оценки модели
    data_collator=collator,                 # коллатор
    processing_class=tokenizer,             # токенизатор
    compute_metrics=compute_metrics         # функция для вычисления метрик
)

Очищаю кэш видеокарты, чтобы разгрузить память

In [5]:
torch.cuda.empty_cache()

После этого, можно начать обучение модели

In [17]:
# запуск обучения модели
trainer.train()

Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

TrainOutput(global_step=630, training_loss=0.7540824451143779, metrics={'train_runtime': 5274.217, 'train_samples_per_second': 1.871, 'train_steps_per_second': 0.119, 'total_flos': 6010414379827200.0, 'train_loss': 0.7540824451143779, 'epoch': 30.0})

Сохраняю полученную модель

In [18]:
# Сохранение модели
model.save_pretrained("./saved_model")

# Сохранение токенизатора
tokenizer.save_pretrained("./saved_model")

('./saved_model\\tokenizer_config.json',
 './saved_model\\special_tokens_map.json',
 './saved_model\\spiece.model',
 './saved_model\\added_tokens.json')

Загружаю модель из файла

In [6]:
# загрузка модели
model = T5ForConditionalGeneration.from_pretrained("./saved_model")

# загрузка токенизатора
tokenizer = T5Tokenizer.from_pretrained("./saved_model")

Далее, опять назначаю устройство вычисление для модели

In [7]:
# привожу модель к устройству
model.to(device)

T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32128, bias=False)
)

Тестирую полученную модель суммаризации:

In [51]:
# индекс строки с примером из датасета
index = 4
# оригинальные текст
orig_text = dataset['validation']['text'][index]
# оригинальная суммаризация
summary = dataset['validation']['summary'][index]
# выводим суммаризацию
print(summary)

Анализируется феномен современного цифрового общества - новый технологический уклад, интегрирующий инфокоммуникативные технологии, радикально и стремительно преобразует ландшафт человеческой телесности, повседневности и духовности. Рассмотрены точки зрения ряда российских исследователей по взаимодействию философии, с одной стороны, и цифровых технологий, с другой, в части формирования системы гуманитарных знаний по цифровой философии и цифровому человеку. Определены смысл и роль философской рефлексии в меняющемся мире в прояснении и систематизации спорных вопросов о статусе человека, в сохранении его подлинно «человеческой» сущности.

Используя реализованную в файле `function.py` функцию `get_summary`, попробую получить суммаризацию данного текста:

In [52]:
# вывожу суммаризацию
generated_sum = get_summary(text=orig_text, 
            tokenizer=tokenizer, 
            model=model, 
            device=device, 
            show_output=True)    # включаю автоматический вывод результатов

>> Original Text: Человечество в очередной раз входит в
эпоху глобальных перемен, на этот раз в эпоху
цифровизации. Хотя каждое поколение, конечно же, может заявить о своей эпохе Великих
перемен и/или потрясений, да и не об одной.
В современном мире, где огромную роль
играет формирующаяся цифровая культура, все
сферы социального бытия и социальной практики, многие области знания трансформируются под воздействием инфокоммуникативных
технологий.
Простое использование цифровых технологий в гуманитарных науках, в первую очередь в философии, вызывает сложности не
только методологического и методического характера, но и неясности в самом определении
области применения.
Исследователь Е. Елькина (2020) подчеркивает, что «Технологическая гонка, знаменующая переход ведущих экономических держав
в шестой технологический уклад, породила
большой поток терминов, в которых «дигитальность» рассматривается как маркер изменений
предметных областей, где эти технологии используются («цифровая экономика», «цифровая революция», «цифровая культура», «цифровая цивилизация», «философия цифрового
мира», «цифровая реальность», «цифровое государство», «цифровой человек»)» [1, с. 58-59].
В цифровом обществе вся жизнедеятельность связана со средствами мультимедиа и информационными технологиями – источники
его генезиса, которые способны быстро и масштабно продвинуть или уничтожить любую
идею (в этом есть и плюс, и минус), что создает
иллюзию «цифрового» дискурса и порождает
огромный поток информации, который ряд авторов называет «цифровым цунами» или «цифровым потопом».
С нашей точки зрения, для данного процесса больше подходит термин «цифровой паводок», т.к. и в случае с природными явлениями (например, весенний паводок рек) происходит постепенное снижение уровня напряжения ситуации – природа сама урегулирует данную проблему с учетом своих природно-климатического, ландшафтного и др. факторов и потом происходит восстановление природной
среды. Аналогична и ситуация с цифровым цунами / цифровым потопом в условиях цифрового мира.
В связи с этим проблема релевантности понятий «цифровая философия» / « Digital
Philosophy» и «цифровой человек» / «Homo
Digital» стала важной: изучение и описание
данных терминов позволит не только понимать
систему современной философии, но и «определить вектор развития человечества с учетом
роли цифровых трансформаций в ноосферогенезе» [1, с. 59].
Но за познанием природного и социального
мира всегда стоит проблема бытия самого человека: философы всегда стремились, стремятся и
будут стремиться понять внутреннюю организацию человеческого существа, мотивы его деятельности, нравственные аспекты его поведения. Поэтому цифровой тренд в гуманитарных
науках имеет наибольшее значение для философии, как способной выявить и определить онтологические, гносеологические и социальные
особенности рефлексии процесса идентификации человека в новых феноменах [2, с. 42].
В данной работе мы будем исходить из
того, что на данном этапе развития общества
передовых государств безусловно приняли две
важные составляющие идейно-технологической (цифровой) революции:
- переход от этапа «информатизации» к
«цифровизации» (понимается авторами как
процесс кодификации);
- формулу «От гуманизма к гуманитаристике» / «From Humanism to the Humanities» [3].
На текущий момент проблематика Digital
Humanities, «цифровой философии» / «Digital
Philosophy» и «цифрового человека» / «Homo
Digital» наиболее изучены и классифицированы в ведущих университетах США, Канады,
Австралии, Голландии, Великобритании и др.
[4, с. 78]. В данной работе мы уделим больше
внимания позициям отечественных исследователей.
Д. Галкин (2011) говорит о необходимости
«философского технологического креационизма как подхода к исследованию искусственной жизни со следующими гносеологические
задачами» [5, с. 32]:
- «философия искусственной жизни не
должна оказаться в плену некритического принятия биологического эволюционизма, трансгуманизма, математического бихевиоризма и
религиознометафизического креационизма с
акцентированием внимания на тотальности искусственной жизни как альтернативном конструировании живого – искусственных технобиотварей»;
- «выработка и критическое прояснение
«сильных» критериев искусственной жизни (на
основе предложенных тезисов) в их отношении
к тем частичным «слабым» решениям, которые
предлагаются в существующих подходах».
Ромащенко А. и Ромащенко М. (2018) в
цифровой философии (Digital Philosophy) выделяют две момента [6, с. 41]:
- с одной стороны, «цифровая философия
вполне ожидаемо фокусируется на визуализационном характере (использование стендов,
моделей, презентаций, схем)», который «раскрывает лишь формальную сторону философии
в ее схематичной ипостаси», но, при этом, «отношения между процессом визуализации и философским рефлексирующим мышлением гораздо сложнее и глубже»;
- с другой стороны, «философская визуализация имеет онтологический статус, заключающийся в трансформации визуального образа от
его символико-образного понимания к онтологии смысла и идеи».
В. Лобовиков (2020) в своих работах пишет
«эта новая идея предполагает дедуктивную организацию формально-логически непротиворечивой системы диамата как фундаментальной
философской теории» где «исходным абстрактно-теоретическим положением, лежащим в основе упомянутой качественно новой
концепции диамата, является весьма нетривиальное допущение, что и метафизика, и диалектика и вообще любая философия как таковая (в
сущности, своей) есть формальная аксиология»
[7, с. 18].
А. Макулин (2016) основываясь на базовых
позициях зарубежных исследователей акцентирует в понятии «цифровая философия» /
«Digital Philosophy» два «смысловых оттенка»
[4, с. 79]:
- «цифровая философия – это направление
в философии и космологии, отделившееся от
цифровой физики с основным предположением» в том, «что Вселенная – это гигантский
тьюринг-полный клеточный автомат» (допускаются «варианты цифровой философии, рассматривающие действительность и акты мышления как процессы обработки информации»);
- «понятие «цифровая философия» используется как некий маркер для обозначения фактов приложения программного обеспечения
для преподавания, анализа или моделирования
классических проблем философии».
С. Тихонова и С. Фролова (2019), как сторонники цифровой антропологи (изучает особенности существования человека в мире, созданном цифровыми, компьютерными технологиями, сетевыми средами, а также последствия влияния виртуальных и технических новаций на человека, исследует его медиазависимость), обращают внимание «на особенность в
сформированной цифровыми технологиями
среде - с одной стороны, ее искусственностью,
с другой – невозможностью отказа от использования «цифры» в современных условиях бытия. Индивиды в цифровом обществе массово включены в процесс отбора технологических
сервисов и решений, доместификация которых
задает потом параметры развития сервисов
электронного государства на макроуровне.
Кроме того, технологическая селекция направляет векторы распределения знания и доступа к
аккумулированному в цифровом пространстве
социальному опыту» [8, с. 289].
В статье Л. Соловьевой (2018) указывется
на «возможности для конструирования индивидом себя самого, собственных образа, имиджа,
биографии, идентичности за счет инфокоммуникативных технологий» и в воображаемом
мире «самостоятельно сформированная личность наделяется новыми атрибутами, как правило, не обязательно совпадающими с реальными, а благодаря виртуальной коммуникации
может представлять собой всего лишь набор
символов, означающих личность, и не нуждаться в физическом теле», но в «этой полиструктуральной сети индивид вынужден постоянно самоидентифицироваться, а установление
идентичности осуществляется через выбор и
принадлежность к определенному дискурсу»
[9, с. 41].
Е. Елькина характеризует [1, с. 60] «цифрового человека» как «узко-специализированного
человека, сформировавшегося под влиянием
конвергентных технологий, киберфизических
систем и искусственного интеллекта» с «отличительной особенностью» производить образы,
«замещающие производство объектов предметной среды человеком постиндустриального общества. Автор считает, что «цифровой человек» и тем более «цифровая цивилизация» не
отражают сущностной характеристики современного человека и общества» и они, «скорее,
символизируют возможные риски утраты человеком собственной идентичности в результате
недооценки роли искусственного интеллекта и
ослабления общественного контроля за развитием цифровых технологий».
Профессор Гурьянова А.В. с соавторами
(2018) делает акцент на том, что «в современных условиях общество выходит на качественно новый виток своей исторической эволюции, который все чаще характеризуется как
"цифровой" или "эпоха цифровизации" и где
формируется особый человеческий тип - "цифровой человек" или "homo digital", обладающий
набором принципиально новых ценностных
ориентаций» [10].
Со своей стороны, мы фиксируем точку
зрения одного из соавторов из ранее опубликованной работы (2021) – «Для "homo digital"
ключевой составляющей эффективной и безопасной жизнедеятельности становится свободное владение цифровыми и информационно-аналитическими технологиями, при помощи которых он получает объем информации,
производит (в силу своей адекватности и способностей) его оценку и выстраивает модель
своего социального поведения [11].
О. Колосова (2018), анализируя характерные черты цифрового общества, приходит к
следующему мнению – «Уникальность цифрового общества заключается в том, что впервые
за всю историю существования человеческая
цивилизация в своем развитии стремится к дематериализации социального бытия. Экономика, социальная коммуникация, культура
представляют собой только знаки: символы,
образы, цифры. Как существовать человеку с
его материальным телом, физиологией, сенсорным восприятием, чувствительностью в этом
идеальном (в философском смысле) мире непонятно. Какова будущность дальнейшего технологического прогресса и развития такой цивилизации – вопрос открытый» [12, с. 80].
Как видим у исследователей на данный момент больше вопросов, чем разрешенных проблем. Смысл и роль философской рефлексии в
меняющемся мире в прояснении спорных вопросов о статусе человека, в сохранении его
подлинно «человеческой» сущности. Именно в
этом и видится задача философии, т.к. указанные дилеммы приобрели беспрецедентное значение: это уже не просто объекты философской
рефлексии, но основополагающими условиями
выживания человечества в современном мире,
в обществе и культуре цифровой эпохи.


>> Generated summary: Статья посвящена исследованию роли философии в формировании цифрового общества в эпоху цифровой трансформации. В статье акцентируется внимание на роли искусственного интеллекта в формировании новых смыслов и моделей бытия человека. Делается вывод о том, что цифровая философия может стать основой для трансформации общества в цифровой мир.

#### Модель для сравнения

Для начала, надо импортировать нужные модули

Тестовая аугментация данных

Собираю все тренировочный суммаризации в один список

In [8]:
summary_data = dataset['train']['summary']
print(len(summary_data))

329

Теперь, я пройдусь по всем известным текстам, и выведу для них суммаризацию

In [9]:
text_data = dataset['train']['processed_text']
print(len(text_data))

329

In [15]:
summ = get_summary(text_data[0], tokenizer, model, device)

In [10]:
sent = []
for text in tqdm(text_data, desc='Суммаризация', unit='text'):
  sent.append(len(text))
  
print(max(sent))
print(int(sum(sent)/len(sent)))
# print(sum(sent))

Суммаризация: 100%|██████████| 329/329 [00:00<?, ?text/s]

14517
6759

In [25]:
torch.cuda.empty_cache()

In [19]:
from tqdm import tqdm
import time

# Пример цикла
progress_bar = tqdm(range(10), desc="Начало")  # Создаем экземпляр прогресс-бара
for i in progress_bar:
    time.sleep(0.5)  # Имитация работы
    progress_bar.set_description(f"Итерация {i}")  # Обновляем описание

Итерация 9: 100%|██████████| 10/10 [00:05<00:00,  1.99it/s]

In [10]:
summaries = []

# Создаем прогресс-бар с начальным описанием
memory = torch.cuda.memory_allocated()
progress_bar = tqdm(text_data, desc=f"Memory allocated: {memory / 1e9:.2f} GB", unit="text")
for text in progress_bar:
    # Память до генерации
    memory = torch.cuda.memory_allocated()
    
    summary = get_summary(text, tokenizer, model, device)
    summaries.append(summary)
    
    progress_bar.set_description(
        f"Memory allocated: {memory / 1e9:.2f} GB"
    )
    
    torch.cuda.empty_cache()

Memory allocated: 0.99 GB: 100%|██████████| 329/329 [22:52<00:00,  4.17s/text]

In [11]:
summary_data = summary_data + summaries

In [40]:
from transformers.utils import TRANSFORMERS_CACHE
import shutil
shutil.rmtree(TRANSFORMERS_CACHE)

In [43]:
import nlpaug.augmenter.word as naw
import random

In [44]:
test_text = data[0]
test_text

'В данной статье указаны основные вопросы, которые ставятся на разрешение перед экспертом в ходе проведения судебной экспертизы сметной стоимости строительства, представлены виды работ, которые необходимо выполнить для установления достоверности сметной документации и приведена информационно-правовая основа, связанная с прохождением экспертной проверки сметной документации.'

In [48]:
# 1. Случайные замены
aug = naw.RandomWordAug(action="swap")
augmented = aug.augment(test_text)

# 2. Удаление слов
aug = naw.RandomWordAug(action="delete", aug_p=0.1)
augmented = aug.augment(test_text)
augmented
# # 3. Генерация опечаток
# aug = naw.KeyboardAug(
#     lang="ru", 
#     aug_char_p=0.1,
#     aug_word_p=0.1
# )

['В данной указаны основные вопросы, которые ставятся на разрешение перед экспертом в ходе проведения судебной экспертизы сметной стоимости строительства, представлены виды работ, которые необходимо для достоверности сметной документации и приведена информационно - основа, с прохождением экспертной проверки сметной документации.']

In [12]:
# создаем список для хранения данных
data = []
# проходимся по каждому тексту в датасете
for i in tqdm(range(len(summary_data)), desc='Собираем данные..', unit='text'):
    # извлекаем текст
    data.append(get_input(summary_data[i]))

Собираем данные..: 100%|██████████| 658/658 [09:14<00:00,  1.19text/s]

In [13]:
# токенизируем данные
tokenized_data = [word_tokenize(summary.lower()) for summary in data]

In [14]:
# создаем объект TaggedDocument
tagged_data = [TaggedDocument(words=words, tags=[str(idx)])
               for idx, words in enumerate(tokenized_data)]

In [15]:
# тренируем модель Doc2Vec
model = Doc2Vec(vector_size=100,            # размер вектора слова или документа
                window=2,                   # размер контекстного окна
                min_count=2,                # минимальная частота слова (игнорирует все, которые встречаются реже указанного значения)
                workers=4,                  # количество потоков
                epochs=100,                 # количество эпох
                dm=0,                       # алгоритм обучения (PV-DM)
                dbow_words=1,               # обучать векторы слов
                alpha=0.025,                # начальная скорость обучения
                min_alpha=0.001,            # минимальная скорость обучения
                negative=20,                # колво шумовых слов
                sample=1e-5,                # порог отсечения частых слов
                seed=42,                    # фиксация сида
                hs=1                        # иерархический софтмакс
                )
model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)
# сохранение
model.save('doc2vec.model')

Нейронная сеть для сравнения успешно обучена

Загружаю модель из файла:

In [16]:
# загрузка
model_sim = Doc2Vec.load('doc2vec.model')

Два пробных текста

In [27]:
text1 = summary_data[1]
text2 = summary_data[330]

Для того чтобы сравнить текста, надо получить эмбеддинги

In [28]:
# вычисляем эмбеддинг
inferred_vector1 = model_sim.infer_vector(word_tokenize(get_input(text1))).reshape(1,-1)
inferred_vector2 = model_sim.infer_vector(word_tokenize(get_input(text2))).reshape(1,-1)

Для вычисления схожести я буду использовать функцию `get_similarity` реализованную в файле `function.py`

In [29]:
similarity = get_similarity(text1, text2, model_sim)
similarity

0.8784244060516357

Было: 0.2992308735847473

In [20]:
print(summary_data)

['В данной статье указаны основные вопросы, которые ставятся на разрешение перед экспертом в ходе проведения судебной экспертизы сметной стоимости строительства, представлены виды работ, которые необходимо выполнить для установления достоверности сметной документации и приведена информационно-правовая основа, связанная с прохождением экспертной проверки сметной документации.', 'Серверные приложения являются критически важными компонентами современной разработки программного обеспечения, поскольку они отвечают за управление конфиденциальными данными, выполнение сложной бизнес-логики и интеграцию с внешними службами. Однако, поскольку частота и серьезность кибератак продолжают расти, важно понимать распространенные уязвимости и угрозы для серверных приложений, чтобы защитить их от атак. В этой статье рассмотрены некоторые наиболее распространенные уязвимости и угрозы для серверных приложений и обсудим способы их устранения.', 'Обеспечение высокого уровня доступности интернет-ресурсов необходимо для пользователей с ограниченными возможностями здоровья и жизнедеятельности. Основной рассматриваемый аспект - проблемы и нарушения зрения. При этом повышение доступности обеспечивается за счет грамотного выбора технических и программных средств, используемых для создания сайта. Важно обеспечить корректное озвучивание элементов сайта программой-скринридером. В рамках данной работы проводится сравнительный анализ WYSIWYG-редакторов, позволяющих людям без навыков программирования наполнять интернет-ресурс контентом. При сравнении учитывалось, насколько создаваемые материалы будут соответствовать требованиям доступности.', 'В работе были проанализированы подходы к оптимизации рендеринга. Проведено экспериментальное исследование, направленное на оценку метрик, объективно отражающих эффективность рендеринга. Результаты эксперимента были рассчитаны для двух приложений, одно из них - на React, который использует Virtual DOM, а второе - на Svelte, показали превосходство Svelte в полтора раза.', 'ѕроводитс€ анализ возможностей использовани€\nJavaScript-библиотек дл€ визуализации данных на сайтах »нтернет,\nописываютс€ наиболее известные из них. –аскрываютс€\nособенности библиотеки D3.js, преимущества ее использовани€ в\nобразовательной сфере. ќписываетс€ пример оформлени€ данных\nжурнала дистанционного класса в виде интерактивного дерева,\nобосновываютс€ преимущества такого вида визуализации.', 'Статья посвящена кафедре биологии и экологии естественно-географического факультета ТувГУ. Показан вклад педагогов-основателей кафедры в создании материально-технической базы и формирование научных направлений.', 'В статье рассматриваются отдельные вопросы правового обеспечения эффективности административно-правового регулирования лицензирования предпринимательской деятельности, связанные с проблемами аннулирования лицензии. Определяется ее правовая природа и необходимость закрепления единообразного порядка судопроизводства по делам об аннулировании лицензии.', 'В статье представлена авторская методика обучения студентов\nнаправленности «Компьютерный дизайн» дисциплине «Программирование на\nJavaScript», которая подразумевает подробное объяснение теоретического\nматериала с разбором решения некоторых задач. Приводится пример изучения\nтемы «Одномерные массивы».', 'Рассматриваются основные преимущества использования PHP, такие как широкое распространение, простота изучения, обширная документация и поддержка крупных сообществом разработчиков. Также подробно рассматриваются недостатки PHP, включая некоторые проблемы с безопасностью, несовершенства в производительности и ограничения в возможностях языка.', 'В статье представлена методика оценки конкурентоспособности дизайн-проектов интерьера, отражающая специфику деятельности предприятий сферы строительного дизайна. Методика построена с использованием интегрального метода оценки конкурентоспособности. Показатели оценки объединены в две группы: потребительские и экономические. Нормирование показателей осуществляется на основе расчета параметрических индексов.', 'Статья посвящена обзору существующих методов написания и организации CSS кода при программировании веб-сайтов.\n\nThe article is devoted to the review of existing methods of writing and organizing CSS code when programming websites.', 'В работе рассмотрена асинхронная методология программирования и ее отличия от синхронной. Описаны такие асинхронные технологии платформы PHP как ReactPHP, Amphp, Swoole. Дана сравнительная характеристика данных технологий и сделаны выводы о целесообразности их применения, а также сформулированы рекомендации, когда использование рассмотренных технологий может быть предпочтительнее. Дана краткая характеристика перспектив развития платформы PHP.', 'ƒанна€ стать€ исследует вли€ние JavaScript на инновации в программировании\nсерверных архитектур, особенно в контексте бессерверных технологий. ¬ ней подчеркиваетс€\nроль JavaScript в преобразовании серверного программировани€ и создании инновационных\nрешений в сфере веб-разработки.', 'В этой статье исследуется влияние React Native на кроссплатформенную мобильную разработку, особое внимание уделяется унифицированному кодированию и модульной архитектуре. В ней рассматривается эволюционирующая роль фреймворка в формировании будущих тенденций.\n\nThis article explores the impact of React Native on cross-platform mobile development, with special attention paid to unified coding and modular architecture. It examines the evolving role of the framework in shaping future trends.', 'В данной статье содержится обзор основных возможностей языков программирования Python и PHP, их применение для решения различных задач. В качестве практической части работы приводится сравнительный анализ их быстродействия на примере выполнения программы, в коде которой используются схожие синтаксические конструкции и одинаковый набор данных на входе; также сравнивается размер исполняемых файлов программы. По результатам анализа делается вывод, позволяющий в целом оценить эффективность применения изучаемых языков и выходные данные об их свойствах, полученные в рамках поставленного эксперимента', 'Обоснована необходимость проектирования среды и ее элементов на принципах инклюзивного дизайна. Рассмотрены основные принципы универсального дизайна. Приведены примеры использования данных принципов в проектной практике. Представлены проекты, выполненные в ТулГУ на основе принципов «дизайна для всех».', 'Статья посвящена возможности и опыту внедрения компьютерных игр в образовательный процесс. Авторы приводят примеры использования игры Minecraft и образовательной платформы MinecraftEdu в российских и зарубежных школах. Изложены причины низкой распространённости MinecraftEdu в России. Приведены точки зрения о положительном и отрицательном влиянии игры Minecraft на успеваемость учащихся и их мотивацию к обучению.', 'В данной статье содержится обзор основных возможностей языков программирования Python и PHP, их применение для решения различных задач. В качестве практической части работы приводится сравнительный анализ их быстродействия на примере выполнения программы, в коде которой используются схожие синтаксические конструкции и одинаковый набор данных на входе; также сравнивается размер исполняемых файлов программы. По результатам анализа делается вывод, позволяющий в целом оценить эффективность применения изучаемых языков и выходные данные об их свойствах, полученные в рамках поставленного эксперимента', 'В статье приводится понятие «методическая модель обучения», обосновывается методическая модель обучения курсантов вузов ФСИН России дисциплине «Русский язык в деловой документации». На основе обзора доступных учебных и учебно-методических источников, анализа документов уточняется цель, определяется содержание работы, характеризуются педагогические и организационные условия обучения (структура занятия, возможные приемы и формы обучения, приводятся рекомендации к средствам обучения и др.). Также в статье рассматривается специфика дисциплины «Русский язык в деловой документации»: обеспечение ведомственной специализации, направленности коммуникативной подготовки курсантов вузов ФСИН России; ориентация на нормативный аспект коммуникации; формирование коммуникативной компетенции исключительно в сфере письменного делового общения.', 'В статье рассматривается экономическое взаимоотношение России и Евросоюза, на примере Германии, являющейся экономическим лидером Евросоюза. Данное сотрудничество рассматривается в историческом и современном контекстах.', 'В статье рассматривается вопрос разработки сайта для компании, которая будет заниматься реализацией мясной продукции. Необходимость информационного ресурса обусловлена необходимостью представления продукции и определения целевой аудитории.', 'В данной статье мы рассмотрели одну из самых популярных профессий на фрилансе- веб-разработчик. Узнали является ли веб-разработка по-прежнему такой же прибыльной профессией, как это было пару лет назад. Поговорили о том, как начинающему веб-разработчику выделиться среди растущего числа конкурентов.', 'В статье рассматривается влияние рекламы, в том числе интернет-рекламы, на общество потребления. Обосновывается мысль, что интернет-реклама оказывает мощное воздействие на массовое сознание и поведение покупателей и является важным источником информации.', 'Разработка интернет-ресурса – это процесс, занимающий продолжительное время и требующий специальных технических знаний для создания качественного веб-сайта, который будет работать как часы.', 'В работе показаны особенности обеспечения информационной безопасности с помощью некоторых способов аутентификации, проведен анализ символьных паролей, биометрической и двухфакторной аутентификации, даны рекомендации пользователям по эффективному использованию двухфакторной аутентификации', 'Психология как отдельное научное знание изучается на протяжении многих лет, однако до сих пор не выработан единый подход к пониманию как личностной, так и общей психологии. В данной статье автор рассматривает сущность и проблематику психологического знания, через призму исторического развития и изучение разных подходов. Исследованию подвергается история психологии, общая психология и психология личности как три взаимосвязанных компонента развития психологической науки, их роль и место в современности.', 'Данная статья посвящена изучению и анализу творчества известного советского архитектора К.С. Мельникова. В статье рассматривается его биография, дана информация о его местах учебы и работы. Представлены отличительные особенности разных периодов творчества Мельникова. Также приводится краткое описание самых главных его сооружений. Автор акцентирует внимание на новаторстве данного архитектора и на художественном языке его проектов. Сделан вывод о том, что К.С. Мельников внес огромный вклад в развитие всей советской архитектуры и стал ярчайшим представителем архитектурного стиля модернизм.', 'По мнению авторов, в настоящее время активизировались поиски новых подходов к анализу таких проявлений человека, как его имидж и визуальные аспекты. Это обусловлено особенностями современной культуры, отличающейся изменениями профессиональных ориентиров современной молодежи. Педагоги художественного образования должны изменить свой подход к татуировке. Их задача – повысить уровень культуры и формировать ответственность в процессе подготовки мастеров тату.', 'В статье рассмотрен опыт применения функциональной музыки - специально подобранных записей музыкальных произведений, которые, звуча во время производственных процессов на промышленных предприятиях могут положительно влиять на духовное и физическое состояние работающих.', 'В статье определены критерии сравнительного анализа фронтенд-фреймворков: тип фреймворка, данные о создателе, лицензии, дате последнего релиза, наличие CLI, используемый синтаксис, рендеринг, связывание данных, архитектура, работа с DOM, гибкость, кривая обучения, скорость написания кода и проведен сравнительный анализ функциональности фреймворков, выявлены особенности применения фреймворков при разработке, сформированы обобщающие таблицы.', 'В статье рассматривается предпроцессор SASS и его основные ключевые аспекты. Рассмотрены определение, основные преимущества и недостатки. В тексте работы также затронута сфера применения этой технологии.', 'В статье рассмотрена взаимосвязь результативности игры от типа темперамента. Даны рекомендации по улучшению тренировочного процесса для одной из игровых специализаций в дисциплине «Боевая арена».', 'В статье рассмотрена проблематика занятости «свободного работника» в современных условиях трудоустройства, а также социальные и экономические эффекты фриланса. Особое внимание уделено цели исследования - положительным и отрицательным сторонам найма удаленного сотрудника для фирмы, государства и самого работника.', 'Данная научная статья посвящена сравнительному анализу двух популярных систем автоматизации бизнес-процессов - 1С:ERP и 1С:КА - с целью определения их преимуществ и недостатков для использования на крупных предприятиях. В статье были рассмотрены основные характеристики и функциональные возможности обеих систем, а также проведен анализ их преимуществ и недостатков. В частности, было выявлено, что 1С:ERP имеет больший функционал и позволяет автоматизировать все управленческие процессы на предприятии, включая производственные, финансовые и кадровые, в то время как 1С:КА ориентирована только на коммерческие процессы. Однако 1С:КА обладает более простым интерфейсом и может быть более удобна для использования в некоторых случаях.', 'Исследуется этико-когнитивная аспектация сообществ. Тест Тьюринга (ТТ) вводится как универсальный интерфейс. Рассмотрены кейсы применения ТТ. ТТ вводится как «фокус поляризации» этики и когнитивности. В сообществах ТТ играет роль фильтра социальностных матриц. Агенты отличаются когнитивной природой. Киборгизация - недостающее звено когнитивной медиации. Между человеком и искусственным интеллектом - когнитивная лестница. ТТ локализует этику ступеней разумности. Искусственные сообщества «генерируют» ТТ-этику.', 'Статья раскрывает вопросы, связанные со спецификой дизайна процесса, исследует системный подход в дизайне, уделяет внимание сближению дизайна и театра, делает акцент на роли процессуального дизайна как эффективного способа комплексного проектирования, раскрывает составляющие дизайна процесса.', 'В статье автор обозначает актуальность и необходимость применения современных средств программирования для облегчения работы в Интернете. В контексте статьи показаны просто- та и доступность CSS и HTML технологий, их применение для повышения информативности веб- иллюстраций. На примере разбирается оформление всплывающего текста, а также затемнение фото под текстом для более четкого и точного его восприятия', 'В данной статье рассмотрены особенности использования ИКТ на уроках технологии. Использование геймификации в процессе изучения таких тем как конструирование и декорирование в начальной школе на уроках технологиина примере популярной компьютерной игры Minecraft.', 'Арфа - это музыкальный инструмент стихии Воды. Арфотерапия способствует структурированию воды, а значит - всех жидких сред в организме человека. Сеансы арфотерапии на природе, в частности, вблизи водоемов, водопадов, более эффективны.', 'В данной статье проводится рассмотрение такой уязвимости web приложений и баз данных как SQL-инъекции. Для того чтобы понять как защитить свои данные или данные своих клиентов, нам понадобится рассмотреть структуру языка SQL и инъекций соответственно, средства разработки web приложений, общие причины уязвимостей баз данных и этапы выполнения данной уязвимости.', 'В данной статье рассмотрены общие принципы парсингаhtml - страниц. Раскрыто понятиетермина «парсинг», приведены примеры его использования. Также определены основные этапы работы парсеров и проблемы их разработки.', 'В данной статье обсуждаются инструменты и технологии,\nнеобходимые для создания безопасного модуля анализа базы данных платформы\n«Green Networking», приведена программная реализация процесса создания\nмодуля. Приведена нормативно-правовая база, регулирующая сбор и анализ\nданных, а также обеспечение безопасности модуля.', 'В данной работе рассматриваются методы построения и управления интеллектуальным домом. Также описывается повышение комфортности, благодаря технологии «Умный дом». Затрагиваются такие функции как: оптимизация освещенности, отопления, защита и управление домом дистанционно, при помощи мобильных устройств и специальных брелоков', 'Статья исследует актуальные вопросы, связанные с ролью кибербезопасности и проблемой экономического шпионажа в контексте международной торговли. Рассматриваются основные аспекты киберпреступности, ее влияние на международные экономические отношения и методы, которые могут быть применены для противодействия этим угрозам. В статье также анализируются современные тенденции в развитии кибербезопасности и выявляются основные направления для обеспечения безопасности в сфере международной торговли.', 'Данная статья посвящена программной платформе Node.js. Рассмотрена его история появления, текущее положение в ряду систем, реализующий аналогичную функциональность, и приведены известные проекты, которые были на нем реализованы. Приведено описание функций веб-сервера, принципа работы с ним, и языка JavaScript, на котором происходит разработка подобных сервисов. Описаны его основные возможности и характерные особенности платформы. Выявлены преимущества и недостатки, а также перспектива платформы в будущем.', 'В статье предлагаются сведения о технологии JWT. О его достоинствах и недостатках в использовании на web - приложениях. Основные методы и использование технологии в реальных условиях.', 'Лермонтов, с полным основанием воспринимаемый как наш современник, остается и мифом, и прежним любимым автором, впитавшим мифологию многих эпох и народов и создавшим неповторимый художественный мир, в свою очередь породивший немало мифов. Значение мифа в сочинениях М. Ю. Лермонтова и мифов о самом авторе видится в начале ХХI века в том, что миф, представляя собой единство познания окружающего мира и осознания роли человека в природе, является основой их когнитивно-концептуальной интерпретации.', 'В данной статье рассматриваются вопросы интернет технологии, в особенности динамичное развитие веб-разработок и веб-приложении, востребованность и разновидности платформ фреймворк технологии в процессе создания сайтов, а также их обзор, программы CMS.', 'В данной статье представлены результаты исследования истории возникновения корсета. Рассматриваются условия развития этого предмета гардероба, цикличность его возвращения в моду и отношение к нему общественности. Представлены результаты анализа роли корсета в творчестве современных дизайнеров.', 'В работе рассматриваются основные барьеры внедрения инновационных разработок в России. Дана подробная характеристика концепции «Умный дом». Дана характеристика основных систем, которые могут быть задействованы в едином комплексе «Умного дома» при внедрении его в многоквартирные дома России. Приведена таблица основных достоинств и недостатков использования концепции «Умный дом».', 'Современное программное обеспечение разрабатывается и поддерживается с использованием систем управления задачами, таких как Github Issues. Элементом таких систем являются задачи одного из типов - «ошибка», «запрос на улучшение» или «вопрос». Классификация типа задачи выполняется вручную и является трудоемкой, зачастую требует глубокого понимания работы программы и знания исходного кода. В статье анализируется использование резервуарной нейронной сети LogNNet и нескольких стандартных алгоритмов классификации для автоматической маркировки отчетов Github. Приводятся результаты работы данных алгоритмов на сбалансированной и несбалансированной базах данных.', 'В данной статье рассмотрены популярные фреймворки, используемые для разработки\nсовременных веб-приложений. Проведен анализ ключевых факторов наиболее популярных фреймворко

In [23]:
# Открываем файл для записи
with open("dataSUKA.txt", "w", encoding="utf-8") as file:
    file.write("\n\n".join(summary_data))  # Объединяем элементы списка в строку

In [ ]:
# функция для извлечения эмбеддингов из всего датасета
def extract_all_embeddings(dataset, part, column, model: Doc2Vec):
    df = pd.DataFrame(columns=['summary', 'embedding'])
    # проходимся по каждой суммаризации в датасете
    for i in tqdm(range(len(dataset[part])), desc='Извлечение эмбеддингов..', unit='text'):
        # получаем суммаризацию
        summary = dataset[part][column][i]
        # получаем эмбеддинг
        embedding = model.infer_vector(word_tokenize(get_input(summary))).reshape(1,-1)
        # сохраняем эмбеддинг
        df.loc[i] = [summary, embedding]
    df.head()
    pd.to_pickle(df, 'all_embs.pkl')

In [ ]:
extract_all_embeddings(dataset, 'train', 'summary', model_sim)

Извлечение эмбеддингов..: 100%|██████████| 329/329 [05:01<00:00,  1.09text/s]

In [ ]:
embs = pd.read_pickle('all_embs.pkl')
embs.head()

,summary,embedding
0,"В данной статье указаны основные вопросы, кото...","[[0.7675859, 0.3641603, 0.95482713, -0.2786018..."
1,Серверные приложения являются критически важны...,"[[0.60429025, -0.579292, 0.6794108, 0.42171627..."
2,Обеспечение высокого уровня доступности интерн...,"[[0.23004857, 0.08845289, -0.056778233, 0.1922..."
3,В работе были проанализированы подходы к оптим...,"[[0.5406296, 0.053741835, 0.11830298, 0.226512..."
4,ѕроводитс€ анализ возможностей использовани€\n...,"[[0.17076421, -0.039292604, 0.34421498, 0.4596..."

для вывода топ 3 самых похожих текстов из датафрейма я буду использовать функцию `find_top_similar` из файла `function.py`

In [ ]:
test_text = dataset['validation']['text'][3]
test_summary = get_summary(test_text, tokenizer, model, device)
# получаю эмбеддинг
embedding = model_sim.infer_vector(word_tokenize(get_input(test_summary))).reshape(1,-1)
# вывожу эмбеддинг
embedding

array([[-0.02756682,  0.06266876, -0.00674738,  0.11523352, -0.2769106 ,
         0.36253974,  0.02930231,  0.04999359, -0.00684423,  0.2039667 ,
        -0.05091163,  0.15339978,  0.16296284,  0.29639333,  0.07788314,
        -0.09428301, -0.31424195, -0.13316733, -0.14294015, -0.02573602,
        -0.41086963, -0.2139987 ,  0.34184104,  0.14831117,  0.05626034,
         0.3023472 , -0.233654  ,  0.2649084 ,  0.06854548, -0.08708176,
        -0.06655807, -0.06988961, -0.04154947,  0.06200563,  0.12485714,
        -0.17591733,  0.20824231, -0.15796858, -0.37414834, -0.20735608,
         0.25030366,  0.02620751,  0.02438718, -0.14121257, -0.05770359,
         0.01544628,  0.14287737,  0.11075833,  0.20310426,  0.08627865,
        -0.03475839, -0.2666585 , -0.0482914 , -0.11744819,  0.13041186,
         0.01486334,  0.13457212, -0.02613166,  0.24559373, -0.1510532 ,
         0.05351738, -0.08953587, -0.3227936 , -0.25935933,  0.15485485,
         0.15480506,  0.02465698, -0.07033521, -0.5433802 ,  0.20663987,
         0.03655927, -0.04759195, -0.23511672,  0.21253394,  0.11629996,
         0.00698694, -0.26922587, -0.13310169,  0.12548195, -0.1484538 ,
         0.0433749 ,  0.0995914 ,  0.02827719,  0.20227629, -0.40329143,
         0.02549001, -0.02299602, -0.26633838,  0.00357462, -0.17023341,
        -0.06319301,  0.27941382,  0.3585352 , -0.14324166,  0.31090814,
         0.00081873, -0.05148794,  0.11671342, -0.13207424, -0.09648678]],
      dtype=float32)

In [ ]:
find_top_similar(embs, embedding)

TypeError: find_top_similar() missing 1 required positional argument: 'model'

## Анализ эффективности модели

## Оптимизация

## Разработка программного продукта

In [ ]:
# TODO 
# - сделать анализ эффективности модель
# - расписать выбор алгоритма
# - проверить лишние ячейки
# - расписать создание API
# - написать документацию
# - ляляля мяу мяу мяу мяу мяумяу